<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>SharpCraft</RootNamespace>
        <ApplicationIcon>game_icon.ico</ApplicationIcon>
    </PropertyGroup>

    <PropertyGroup Condition="'$(RuntimeIdentifier)' == 'win-x64'">
        <OutputType>WinExe</OutputType>
    </PropertyGroup>

    <ItemGroup>
      <None Update="soft_oal.dll" Condition="'$(RuntimeIdentifier)' == 'win-x64'">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>

      <ProjectReference Include="..\SharpCraft.Engine\SharpCraft.Engine.csproj" />
      <ProjectReference Include="..\SharpCraft.Game\SharpCraft.Game.csproj" />

      <ResourceFiles Include="..\SharpCraft.Game\Resources\**\*" />
    </ItemGroup>

    <Target Name="BuildResources" AfterTargets="Build"
          Inputs="@(ResourceFiles)"
          Outputs="$(OutputPath)Resources.scres">
      <ZipDirectory SourceDirectory="..\SharpCraft.Game\Resources"
                    DestinationFile="$(OutputPath)Resources.scres"
                    Overwrite="true" />
    </Target>

    <Target Name="BuildResourcesPublish" AfterTargets="Publish">
        <ZipDirectory SourceDirectory="..\SharpCraft.Game\Resources"
                      DestinationFile="$(PublishDir)Resources.scres"
                      Overwrite="true" />
    </Target>
    
</Project>
