<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <RootNamespace>SharpCraft.Editor</RootNamespace>
        <AssemblyTitle>SharpCraft Editor</AssemblyTitle>
    </PropertyGroup>

    <PropertyGroup Condition="'$(RuntimeIdentifier)' == 'win-x64' or '$(RuntimeIdentifier)' == 'win-x86'">
        <OutputType>WinExe</OutputType>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\SharpCraft.Engine\SharpCraft.Engine.csproj" />
    </ItemGroup>

    <Import Project="..\eng\Resources.targets" />

</Project>