<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <EmbeddedResource Include="Shaders/**/*.vert" />
        <EmbeddedResource Include="Shaders/**/*.frag" />

        <PackageReference Include="DiscordRichPresence" />
        <PackageReference Include="FontStashSharp" />
        <PackageReference Include="FontStashSharp.Rasterizers.StbTrueTypeSharp" />
        <PackageReference Include="Miniaudio-CS" />
        <PackageReference Include="NVorbis" />
        <PackageReference Include="Silk.NET" />
        <PackageReference Include="Silk.NET.Input.Glfw" />
        <PackageReference Include="StbImageSharp" />
    </ItemGroup>

</Project>